# Gradle
org.gradle.jvmargs=-Xmx16048m -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
# Kotlin
kotlin.code.style=official
# Android
android.useAndroidX=true
android.nonTransitiveRClass=true
# MPP
kotlin.mpp.enableCInteropCommonization=true
# Native
kotlin.incremental.native=true
# Compose
org.jetbrains.compose.experimental.uikit.enabled=true
org.jetbrains.compose.experimental.jscanvas.enabled=true
# NoiseCapture
appNamespace=org.noiseplanet.noisecapture
appPackageName=org.noiseplanet.noisecapturekmp
appVersionName=0.7.1
appVersionCode=10
