name: Feature Request
description: Suggest a feature or improvement.
title: Feature Request
labels:
  - needs triage
assignees:
  - tonelli-m
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of the problem or missing capability.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: If you already have a solution in mind, please describe it!
  - type: markdown
    attributes:
      value: Thanks for taking the time to help us improve NoiseCapture!
